package main

import (
	"io"
	"text/template"
	"time"
)

type PreambleField struct {
	Name, SetupFn string
}

func OutputPreamble(w io.Writer, name string, args ...PreambleField) error {
	return TmplPreamble.Execute(w, struct {
		Time       time.Time
		StructName string
		Args       []PreambleField
	}{time.Now(), name, args})
}

var TmplPreamble = template.Must(template.New("preamble").Parse(`package main

//WARNING: generated by go-stylus ({{.Time.Unix}})

import (
	"reflect"
	"bytes"

	"github.com/af-afk/stylus"
)

//go:inline
func unsafePtr(x any) int32 {
	return *(*int32)(reflect.ValueOf(x).UnsafePointer())
}

//export user_entrypoint
func userEntrypoint(cdlen int32) int32 {
	stylus.PayForMemoryGrow(0)
	args := make([]byte, cdlen)
	stylus.ReadArgs(unsafePtr(&args))
	var rd []byte
	defer func() {
		stylus.StorageFlushCache(false)
		stylus.WriteResult(unsafePtr(&rd), int32(len(rd)))
	}()
	if len(args) < 4 {
		return 1
	}
	var sr {{.StructName}}
	{{range .Args}}sr.{{.Name}} = {{.SetupFn}}(){{end}}`,
))
