package main

//WARNING: generated by go-stylus (1739000981)

import (
	"reflect"
	"bytes"

	"github.com/af-afk/stylus"
)

//go:inline
func unsafePtr(x any) int32 {
	return *(*int32)(reflect.ValueOf(x).UnsafePointer())
}

//export user_entrypoint
func userEntrypoint(cdlen int32) int32 {
	stylus.PayForMemoryGrow(0)
	args := make([]byte, cdlen)
	stylus.ReadArgs(unsafePtr(&args))
	var rd []byte
	defer func() {
		stylus.StorageFlushCache(false)
		stylus.WriteResult(unsafePtr(&rd), int32(len(rd)))
	}()
	if len(args) < 4 {
		return 1
	}
	var sr Storage
	sr.Counter = stylus.NewStorageUint256()
	if bytes.Equal(args[:4], []byte{66,150,108,104,}) {
		if len(args) != 4 + 32 {
			return 1
		}
		x0, err := stylus.BUint256ToBig(args[4+(0*32):4+32+(0*32)])
		if err != nil {
			return 1
		}
		rd, err = sr.Burn(x0,)
		if err != nil {
			return 1
		} else {
			return 0
		}
	}
	return 1
}
