package main

// Code generated by github.com/af-afk/stylus version d9b9dc5526cc252898684ab0b5efde091ecf99d8

import (
	"reflect"
	"bytes"

	"github.com/af-afk/stylus"
)

//go:inline
func unsafePtr(x any) int32 {
	return *(*int32)(reflect.ValueOf(x).UnsafePointer())
}

//export user_entrypoint
func userEntrypoint(cdlen int32) int32 {
	stylus.PayForMemoryGrow(0)
	args := make([]byte, cdlen)
	stylus.ReadArgs(unsafePtr(&args))
	var rc int32
	defer func() {
		stylus.StorageFlushCache(false)
		stylus.WriteResult(unsafePtr(&stylus.Rd), int32(len(stylus.Rd)))
	}()
	if len(args) < 4 {
		return 1
	}
	var sr Storage
	sr.Counter = stylus.NewStorageUint256()
	defer func() {
		if r := recover(); r != nil {
			rc = 1
		}
	}()
	
	// Add
	if bytes.Equal(args[:4], []byte{16,3,226,210,}) {
		var err error
		if len(args) != 4 + 32 {
			return 1
		}
		x0, err := stylus.BUint256ToBig(args[4+(0*32):4+32+(0*32)])
		if err != nil {
			return 1
		}
		rdAdd, err := sr.Add(x0,)
		if err != nil {
			return 1
		} else {
			return 0
		}
		if rc != 0 {
			return rc
		}
		stylus.Rd = append(stylus.Rd, stylus.BigToInt256Bytes(rdAdd)...)
	}
	// Sub
	if bytes.Equal(args[:4], []byte{250,59,214,197,}) {
		var err error
		if len(args) != 4 + 32 {
			return 1
		}
		x0, err := stylus.BInt256ToBig(args[4+(0*32):4+32+(0*32)])
		if err != nil {
			return 1
		}
		rdSub, err := sr.Sub(x0,)
		if err != nil {
			return 1
		} else {
			return 0
		}
		if rc != 0 {
			return rc
		}
		stylus.Rd = append(stylus.Rd, stylus.Uint256ToBytes(rdSub)...)
	}
	// Count
	if bytes.Equal(args[:4], []byte{6,102,26,189,}) {
		var err error
		if len(args) != 4 + 0 {
			return 1
		}
		rdCount, err := sr.Count()
		if err != nil {
			return 1
		} else {
			return 0
		}
		if rc != 0 {
			return rc
		}
		stylus.Rd = append(stylus.Rd, stylus.BigToInt256Bytes(rdCount)...)
	}
	// Add
	if bytes.Equal(args[:4], []byte{16,3,226,210,}) {
		var err error
		if len(args) != 4 + 32 {
			return 1
		}
		x0, err := stylus.BUint256ToBig(args[4+(0*32):4+32+(0*32)])
		if err != nil {
			return 1
		}
		rdAdd, err := sr.Add(x0,)
		if err != nil {
			return 1
		} else {
			return 0
		}
		if rc != 0 {
			return rc
		}
		stylus.Rd = append(stylus.Rd, stylus.BigToInt256Bytes(rdAdd)...)
	}
	// Sub
	if bytes.Equal(args[:4], []byte{250,59,214,197,}) {
		var err error
		if len(args) != 4 + 32 {
			return 1
		}
		x0, err := stylus.BInt256ToBig(args[4+(0*32):4+32+(0*32)])
		if err != nil {
			return 1
		}
		rdSub, err := sr.Sub(x0,)
		if err != nil {
			return 1
		} else {
			return 0
		}
		if rc != 0 {
			return rc
		}
		stylus.Rd = append(stylus.Rd, stylus.Uint256ToBytes(rdSub)...)
	}
	// Count
	if bytes.Equal(args[:4], []byte{6,102,26,189,}) {
		var err error
		if len(args) != 4 + 0 {
			return 1
		}
		rdCount, err := sr.Count()
		if err != nil {
			return 1
		} else {
			return 0
		}
		if rc != 0 {
			return rc
		}
		stylus.Rd = append(stylus.Rd, stylus.BigToInt256Bytes(rdCount)...)
	}
	return 1
}
