package internal

import (
	"io"
	"runtime/debug"
	"text/template"
)

type PreambleField struct {
	Name, SetupFn string
}

func OutputPreamble(w io.Writer, name string, args ...PreambleField) error {
	// Get the release info of the binary that we have.
	rev := "unknown"
	if info, ok := debug.ReadBuildInfo(); ok {
		for _, s := range info.Settings {
			if s.Key == "vcs.revision" {
				rev = s.Value
			}
		}
	}
	return TmplPreamble.Execute(w, struct {
		Rev        string
		StructName string
		Args       []PreambleField
	}{rev, name, args})
}

var TmplPreamble = template.Must(template.New("preamble").Parse(`package main

// Code generated by github.com/af-afk/stylus version {{.Rev}}

import (
	"reflect"
	"bytes"

	"github.com/af-afk/stylus"
)

//go:inline
func unsafePtr(x any) int32 {
	return *(*int32)(reflect.ValueOf(x).UnsafePointer())
}

//export user_entrypoint
func userEntrypoint(cdlen int32) int32 {
	stylus.PayForMemoryGrow(0)
	args := make([]byte, cdlen)
	stylus.ReadArgs(unsafePtr(&args))
	var rc int32
	defer func() {
		stylus.StorageFlushCache(false)
		stylus.WriteResult(unsafePtr(&stylus.Rd), int32(len(stylus.Rd)))
	}()
	if len(args) < 4 {
		return 1
	}
	var sr {{.StructName}}{{range .Args}}
	sr.{{.Name}} = {{.SetupFn}}(){{end}}
	defer func() {
		if r := recover(); r != nil {
			rc = 1
		}
	}()
	`,
))
