package main

// Code generated by github.com/af-afk/stylus version 821d25df006d0c43c9cca1d0d4c48aaeb108bfc2

import (
	"reflect"
	"bytes"

	stylusHost "github.com/af-afk/stylus/host"
	"github.com/af-afk/stylus"
)

//go:inline
func unsafePtr(x any) int32 {
	return *(*int32)(reflect.ValueOf(x).UnsafePointer())
}

//export user_entrypoint
func userEntrypoint(cdlen int32) int32 {
	stylusHost.PayForMemoryGrow(0)
	args := make([]byte, cdlen)
	stylusHost.ReadArgs(unsafePtr(&args))
	var rc int32
	defer func() {
		stylusHost.StorageFlushCache(false)
		stylusHost.WriteResult(unsafePtr(&stylus.Rd), int32(len(stylus.Rd)))
	}()
	if len(args) < 4 {
		return 1
	}
	var sr Storage
	defer func() {
		if r := recover(); r != nil {
			rc = 1
		}
	}()
	
	// Revert
	if bytes.Equal(args[:4], []byte{125,163,195,171,}) {
		var err error
		if len(args) != 4 + 0 {
			return 1
		}
		err = sr.Revert()
		if err != nil {
			if d, ok := stylus.IsStylusErr(err); ok {
				stylus.Rd = d
			}
			return 1
		} else {
			return 0
		}
		if rc != 0 {
			return rc
		}
		
	}
	// Revert
	if bytes.Equal(args[:4], []byte{125,163,195,171,}) {
		var err error
		if len(args) != 4 + 0 {
			return 1
		}
		err = sr.Revert()
		if err != nil {
			if d, ok := stylus.IsStylusErr(err); ok {
				stylus.Rd = d
			}
			return 1
		} else {
			return 0
		}
		if rc != 0 {
			return rc
		}
		
	}
	return 1
}
